# Generated by Django 4.2 on 2025-07-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('source_domain', models.CharField(max_length=128)),
                ('prediction', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('sentiment', models.CharField(max_length=32)),
                ('sentiment_score', models.FloatField()),
                ('entities', models.TextField()),
                ('trust_score', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
