# Generated by Django 4.2 on 2025-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleanalysis',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
