# Generated by Django 5.2.4 on 2025-07-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articleanalysis_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleanalysis',
            name='category',
        ),
    ]
