# Generated by Django 4.2.7 on 2025-08-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_domaintrust_flaggedcontent_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlaggedContent',
        ),
    ]
